"""
Django settings for bus_booking_backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import logging
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = False
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@*d0(4)z&)d#9ctm6f(@7vmf_iqil-9#2-n_g7k0yl&o9*#wpl'
# EasyPay Mobile Money API settings
EASYPAY_MOBILE_MONEY_API_KEY = 'your_mobile_money_api_key'
EASYPAY_MOBILE_MONEY_API_URL = 'https://api.easypay.co.ug/mobilemoney'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'bookings',
    'rest_framework',  # Add Django REST framework
    'rest_framework.authtoken',  # Add Token Authentication
    'rest_framework_simplejwt',

    
]


AUTH_USER_MODEL = 'bookings.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bookings.middleware.CustomCSRFMiddleware',
    'bookings.middleware.RemoveNewlinesMiddleware',
    'bookings.middleware.CleanRequestMiddleware',
]


ROOT_URLCONF = 'bus_booking_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bus_booking_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CORS_ALLOW_ALL_ORIGINS = True  # For development purposes; change to specific origins in production


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
                'rest_framework.authentication.TokenAuthentication',

    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
        'rest_framework.permissions.IsAuthenticated',  
    ),
}

# Add trusted origins if needed
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',        # Localhost development
    'http://localhost:19006',       # Another localhost for your app
    'http://127.0.0.1:8000',
    'http://localhost:8000',           # Localhost
    'https://web-production-84665.up.railway.app'  # Production URL
]

CORS_ALLOWED_ORIGINS = [
    'https://web-production-84665.up.railway.app',  # Production URL
    'http://localhost:3000',                        # Localhost development
    'http://localhost:19006',                       # Another localhost for your app
    'http://127.0.0.1:8000',
    "http://127.0.0.1:3000",

]

# Allow specific headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-api-key',  # Add your custom header here
]


# Development setting (only for testing, not recommended for production)
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False  # Should be False to allow JS access
CSRF_USE_SESSIONS = False  # Generally set to False for API endpoints
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # To log the failures for debugging


# Set up logging for CSRF issues
logger = logging.getLogger('django.security.csrf')
logger.setLevel(logging.DEBUG)

LOGIN_URL = '/api/login/'



