# Generated by Django 5.0.6 on 2024-07-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_routes',
            field=models.CharField(choices=[('KSE', 'Kasese'), ('AR', 'Arua'), ('ML', 'Malaba'), ('KBL', 'Kabale'), ('KPL', 'Kampala'), ('MB', 'Mbarara'), ('CN', 'Cyanika'), ('NB', 'Nairobi'), ('KG', 'Kigali'), ('JB', 'Juba'), ('GM', 'Goma'), ('GL', 'Gulu'), ('SR', 'Soroti'), ('MY', 'Moyo'), ('KS', 'Kisoro')], default='KPL', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(choices=[('WT', 'Kasese'), ('NT', 'Arua'), ('ET', 'Malaba'), ('ST', 'Kabale'), ('CT', 'Kampala')], default='KPL', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(choices=[('HB', 'Horizon Bus'), ('BC', 'Busscar'), ('GBC', 'Gaaga Bus Company'), ('JEC', 'Jaguar Executive Coaches'), ('KC', 'Kampala Coach'), ('MBS', 'Mash Bus Services'), ('MC', 'Modern Coast'), ('QC', 'Queens Coach'), ('UPB', 'Uganda Post Bus'), ('KB', 'Kalita Bus'), ('BBC', 'Baby Coach'), ('KH', 'Kampala Hopper'), ('LK', 'Link Bus'), ('NC', 'Nile Coach')], max_length=100),
        ),
    ]
