# Generated by Django 5.0.6 on 2024-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
