# Generated by Django 5.0.6 on 2024-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bus_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
