# Generated by Django 5.0.6 on 2024-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bus_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
